bases:
  - ../../base
patchesJSON6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: myapp
    path: patchdep.yaml
  - target:
      version: v1
      kind: Service
      name: myapp
    path: patchsvc.yaml
